---
- name: install unzip
  package: name=unzip state=present
  become: true

- name: create user
  user:
    name: consul
    system: true
    shell: /usr/sbin/nologin
    state: present
  become: true

- name: create config dir
  file: path=/etc/consul.d mode="0755" state=directory
  become: true

- name: create data dir
  file: path=/srv/consul/localhost mode="0755" owner=consul group=consul state=directory
  become: true

- name: install
  unarchive:
    src: "{{ consul_download_url }}"
    dest: /usr/local/bin
    creates: /usr/local/bin/consul
    remote_src: true
    owner: root
    group: root
    mode: "0755"
  become: true

- name: install environment file
  copy:
    src: etc/sysconfig/consul-server
    dest: /etc/sysconfig/consul-server
    owner: root
    group: root
    mode: "0644"
  register: consul_environment
  become: true

- name: install systemd unit
  copy:
    src: etc/systemd/consul-server.service
    dest: /etc/systemd/system/consul-server.service
    owner: root
    group: root
    mode: "0644"
  register: consul_systemd_unit
  become: true

- name: start consul server
  systemd:
    name: consul-server.service
    enabled: true
    state: |-
      {%- if consul_systemd_unit | changed or consul_environment | changed -%}
        restarted
      {%- else -%}
        started
      {%- endif -%}
    daemon_reload: "{{ consul_systemd_unit | changed }}"
  become: true
