---
dist: trusty
sudo: false

matrix:
  allow_failures:
    rust: nightly
  fast_finish: true

language: rust
rust:
  - stable
  - nightly

script: cargo test

notifications:
  email:
    on_success: never
    on_failure: never
