[package]
name = "rusty"
version = "0.1.0"
authors = ["Naftuli Kay <me@naftuli.wtf>"]

[dependencies]
argparse = "0.2.*"
chan = "0.1.*"
chan-signal = "0.3.*"
consul = "0.1"
backoff = "0.1.*"
hyper = "0.10.*"
iron = "0.5.*"
log = "0.3.*"
log4rs = "0.7.*"
