---
- name: configure vagrant
  hosts: all
  become: true
  roles:
    - role: vagrant-rust-dev
    - role: consul-server
    - role: openresty
    - role: dnsmasq
  tasks:
    - name: be an adult
      selinux: state=enforcing policy=targeted
